# Generated by Django 4.2.4 on 2024-05-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=11)),
                ("dsg", models.CharField(max_length=20)),
                ("salary", models.ImageField(upload_to="")),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
            ],
        ),
    ]
